CREATE DATABASE IF NOT EXISTS recipe_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE recipe_db;

CREATE TABLE IF NOT EXISTS recipe (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    title VARCHAR(255) NOT NULL COMMENT '菜谱标题',
    description TEXT COMMENT '菜谱描述',
    cover_image VARCHAR(500) COMMENT '封面图片',
    author VARCHAR(100) COMMENT '作者',
    cook_time INT COMMENT '烹饪时间(分钟)',
    difficulty TINYINT COMMENT '难度:1-简单,2-中等,3-困难',
    favorite_count INT DEFAULT 0 COMMENT '收藏数',
    view_count INT DEFAULT 0 COMMENT '浏览数',
    tags VARCHAR(500) COMMENT '标签,逗号分隔',
    ingredients TEXT COMMENT '食材清单(JSON)',
    steps TEXT COMMENT '烹饪步骤(JSON)',
    tips TEXT COMMENT '小贴士',
    status TINYINT DEFAULT 1 COMMENT '状态:0-下架,1-上架',
    is_draft TINYINT DEFAULT 0 COMMENT '是否草稿:0-否,1-是',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除:0-未删,1-已删',
    INDEX idx_status (status, is_draft, deleted),
    INDEX idx_favorite (favorite_count),
    INDEX idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜谱表';

CREATE TABLE IF NOT EXISTS favorite (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    recipe_id BIGINT NOT NULL COMMENT '菜谱ID',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    deleted TINYINT DEFAULT 0 COMMENT '逻辑删除:0-未删,1-已删',
    UNIQUE KEY uk_user_recipe (user_id, recipe_id, deleted),
    INDEX idx_recipe (recipe_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='收藏表';

INSERT INTO recipe (title, description, cover_image, author, cook_time, difficulty, favorite_count, view_count, tags, ingredients, steps, tips, status, is_draft) VALUES
('红烧五花肉', '经典家常菜，肥而不腻，入口即化', 'https://images.unsplash.com/photo-1623689046286-01d812ba6d10?w=800&h=500&fit=crop', '美食达人', 60, 2, 1286, 5621, '川菜,家常菜,下饭神器', 
'[{"name":"五花肉","amount":"500g","note":"选三层肉最佳"},{"name":"生抽","amount":"2勺","note":""},{"name":"老抽","amount":"1勺","note":"上色用"},{"name":"冰糖","amount":"30g","note":""},{"name":"料酒","amount":"2勺","note":""},{"name":"姜片","amount":"5片","note":""},{"name":"八角","amount":"2个","note":""},{"name":"桂皮","amount":"1小块","note":""},{"name":"盐","amount":"适量","note":""}]',
'[{"content":"五花肉切成2-3厘米见方的块，冷水下锅，加入姜片和料酒，大火烧开后焯水3分钟，捞出洗净沥干。","image":""},{"content":"锅中放少许油，加入冰糖小火炒出糖色，注意火候不要太大，避免炒糊。","image":""},{"content":"放入焯水后的五花肉，翻炒均匀，让每一块肉都裹上糖色。","image":""},{"content":"加入生抽、老抽、料酒，放入八角、桂皮、剩余的姜片，翻炒出香味。","image":""},{"content":"加入没过肉的热水，大火烧开后转小火，盖上锅盖炖煮45分钟。","image":""},{"content":"最后大火收汁，根据口味加适量盐调味，汤汁浓稠即可出锅。","image":""}]',
'1. 焯水要冷水下锅，能更好地去除血水和腥味\n2. 炒糖色要用小火，颜色变成枣红色即可\n3. 加水一定要加热水，肉质才不会柴\n4. 最后收汁不要收太干，留一点汤汁拌饭超好吃',
1, 0),
('番茄炒蛋', '最简单也最困难的国民家常菜', 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=500&fit=crop', '小厨神', 15, 1, 2341, 8932, '家常菜,快手菜,午餐',
'[{"name":"鸡蛋","amount":"3个","note":""},{"name":"番茄","amount":"2个","note":"选熟透的"},{"name":"葱花","amount":"适量","note":""},{"name":"盐","amount":"适量","note":""},{"name":"白糖","amount":"1勺","note":"提鲜"},{"name":"食用油","amount":"适量","note":""}]',
'[{"content":"鸡蛋打散，加少许盐搅拌均匀；番茄切块，大小适中。","image":""},{"content":"热锅凉油，油温六成热时倒入蛋液，快速划散，炒至八成熟盛出备用。","image":""},{"content":"锅中留底油，放入番茄块翻炒，加一勺白糖，炒出番茄汁。","image":""},{"content":"倒入炒好的鸡蛋，快速翻炒均匀，加盐调味。","image":""},{"content":"出锅前撒上葱花即可。","image":""}]',
'1. 鸡蛋加少许温水打散，炒出来更嫩\n2. 番茄加白糖可以中和酸味，更鲜美\n3. 全程大火快炒，鸡蛋才不会老',
1, 0),
('宫保鸡丁', '川菜经典，鸡肉滑嫩，花生酥脆', 'https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&h=500&fit=crop', '川菜大师', 30, 2, 1892, 7234, '川菜,经典,晚餐',
'[{"name":"鸡胸肉","amount":"300g","note":"或鸡腿肉"},{"name":"花生米","amount":"50g","note":"熟花生"},{"name":"干辣椒","amount":"10个","note":""},{"name":"花椒","amount":"1勺","note":""},{"name":"葱姜蒜","amount":"适量","note":""},{"name":"生抽","amount":"2勺","note":""},{"name":"醋","amount":"1勺","note":""},{"name":"白糖","amount":"1勺","note":""},{"name":"淀粉","amount":"适量","note":""}]',
'[{"content":"鸡胸肉切丁，加生抽、料酒、淀粉腌制15分钟。","image":""},{"content":"调碗汁：生抽、醋、白糖、淀粉、少许水搅匀备用。","image":""},{"content":"花生米炸至金黄酥脆，捞出备用。","image":""},{"content":"锅中热油，放入干辣椒和花椒爆香。","image":""},{"content":"放入腌制好的鸡丁快速滑炒至变色。","image":""},{"content":"加入葱姜蒜翻炒，倒入碗汁翻炒均匀。","image":""},{"content":"出锅前加入花生米，翻炒几下即可。","image":""}]',
'1. 花生米最后放才会保持酥脆\n2. 鸡肉用淀粉腌制才会滑嫩\n3. 碗汁提前调好，避免手忙脚乱',
1, 0),
('清蒸鲈鱼', '粤式蒸鱼，鲜嫩爽滑，原汁原味', 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=800&h=500&fit=crop', '粤菜名厨', 25, 2, 1567, 6123, '粤菜,海鲜,宴请',
'[{"name":"鲈鱼","amount":"1条","note":"约500g"},{"name":"葱姜","amount":"适量","note":""},{"name":"蒸鱼豉油","amount":"2勺","note":""},{"name":"料酒","amount":"1勺","note":""},{"name":"盐","amount":"少许","note":""},{"name":"食用油","amount":"适量","note":""}]',
'[{"content":"鲈鱼处理干净，两面划几刀，抹上盐和料酒腌制10分钟。","image":""},{"content":"盘底铺上葱姜丝，放上鲈鱼，鱼肚内也塞入葱姜。","image":""},{"content":"水开后上锅蒸8-10分钟，根据鱼的大小调整时间。","image":""},{"content":"蒸好后倒掉盘中汁水，去掉葱姜。","image":""},{"content":"铺上新鲜葱丝，淋上蒸鱼豉油。","image":""},{"content":"烧热油，浇在葱丝上激出香味即可。","image":""}]',
'1. 鱼要新鲜，活鱼清蒸最好\n2. 蒸的时间要掌握好，鱼肉刚熟最嫩\n3. 最后淋热油是关键，香味马上出来',
1, 0),
('麻婆豆腐', '麻辣鲜香，下饭神器', 'https://images.unsplash.com/photo-1582576163090-09d3b6f8a969?w=800&h=500&fit=crop', '四川厨子', 20, 1, 2103, 6789, '川菜,家常菜,午餐',
'[{"name":"嫩豆腐","amount":"1块","note":"南豆腐"},{"name":"猪肉末","amount":"100g","note":""},{"name":"郫县豆瓣酱","amount":"1勺","note":""},{"name":"花椒粉","amount":"适量","note":""},{"name":"辣椒粉","amount":"1勺","note":""},{"name":"蒜末","amount":"适量","note":""},{"name":"葱花","amount":"适量","note":""},{"name":"生抽","amount":"1勺","note":""},{"name":"淀粉","amount":"适量","note":""}]',
'[{"content":"豆腐切小块，开水焯烫2分钟捞出备用。","image":""},{"content":"锅中热油，放入肉末炒散炒香。","image":""},{"content":"加入豆瓣酱、蒜末炒出红油。","image":""},{"content":"加入适量清水，放入豆腐轻轻推动。","image":""},{"content":"加生抽调味，小火煮3分钟入味。","image":""},{"content":"水淀粉勾芡，撒上花椒粉和葱花即可。","image":""}]',
'1. 豆腐焯水可以去除豆腥，也不容易碎\n2. 推豆腐要轻，别把豆腐弄碎了\n3. 花椒粉最后撒，麻香味才浓',
1, 0),
('白切鸡', '粤菜经典，皮爽肉滑', 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&h=500&fit=crop', '广东阿婆', 45, 2, 1456, 5678, '粤菜,经典,宴请',
'[{"name":"三黄鸡","amount":"1只","note":"约1.5kg"},{"name":"姜","amount":"1块","note":""},{"name":"葱","amount":"适量","note":""},{"name":"料酒","amount":"2勺","note":""},{"name":"盐","amount":"适量","note":""},{"name":"蘸料","amount":"适量","note":"姜葱酱"}]',
'[{"content":"鸡处理干净，冷水下锅，加入姜葱、料酒。","image":""},{"content":"大火烧开后转小火，浸煮25分钟。","image":""},{"content":"煮好后捞出，立即放入冰水中浸泡15分钟。","image":""},{"content":"捞出沥干水分，斩块装盘。","image":""},{"content":"配上姜葱蘸料即可食用。","image":""}]',
'1. 水开后转小火，保持微沸状态，鸡肉才嫩\n2. 冰水浸泡是皮爽肉滑的关键\n3. 蘸料要用热葱油浇，香味才出得来',
1, 0),
('糖醋排骨', '酸甜可口，老少皆宜', 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=500&fit=crop', '巧手妈妈', 40, 2, 1789, 6234, '家常菜,浙菜,晚餐',
'[{"name":"排骨","amount":"500g","note":"肋排"},{"name":"生抽","amount":"2勺","note":""},{"name":"料酒","amount":"2勺","note":""},{"name":"醋","amount":"3勺","note":""},{"name":"白糖","amount":"4勺","note":""},{"name":"番茄酱","amount":"2勺","note":""},{"name":"姜片","amount":"适量","note":""},{"name":"白芝麻","amount":"适量","note":""}]',
'[{"content":"排骨冷水下锅焯水，捞出洗净沥干。","image":""},{"content":"锅中热油，放入排骨煎至两面金黄。","image":""},{"content":"加入生抽、料酒、醋、白糖、番茄酱，翻炒均匀。","image":""},{"content":"加入没过排骨的热水，大火烧开转小火煮30分钟。","image":""},{"content":"大火收汁，汤汁浓稠包裹住排骨。","image":""},{"content":"出锅撒上白芝麻即可。","image":""}]',
'1. 糖醋比例是关键，记住1酒2酱3醋4糖\n2. 收汁要不停翻炒，避免糊底\n3. 加番茄酱颜色更好看，味道更丰富',
1, 0),
('水煮鱼', '麻辣鲜香，鱼片滑嫩', 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=500&fit=crop', '辣味人生', 50, 3, 1234, 4567, '川菜,海鲜,夜宵',
'[{"name":"草鱼","amount":"1条","note":"约2kg"},{"name":"豆芽","amount":"200g","note":""},{"name":"干辣椒","amount":"大量","note":""},{"name":"花椒","amount":"大量","note":""},{"name":"郫县豆瓣酱","amount":"2勺","note":""},{"name":"葱姜蒜","amount":"适量","note":""},{"name":"蛋清","amount":"1个","note":""},{"name":"淀粉","amount":"适量","note":""}]',
'[{"content":"鱼片切片，加蛋清、淀粉、盐腌制20分钟。","image":""},{"content":"豆芽焯水，铺在碗底。","image":""},{"content":"锅中热油，放入豆瓣酱、葱姜蒜炒出红油。","image":""},{"content":"加入清水或高汤，烧开后下入鱼片。","image":""},{"content":"鱼片变白即可捞出，放在豆芽上。","image":""},{"content":"表面撒上干辣椒、花椒，淋上热油激香。","image":""}]',
'1. 鱼片要切薄，腌制才入味\n2. 鱼片下锅后不要频繁搅动，避免碎掉\n3. 最后淋热油油温要高，才能激出香味',
1, 0);